### ISSUE TITLE
一些疑惑

### ISSUE THREAD

**Issue by leileilin** [THUNLP-MT/THUMT#110]
你好，
train文件夹下的events.out.tfevents.1638169963.NLPGPU10-2.29554.0文件是代表什么？
非常感谢！

**Comment by GrittyChen** [comment]
> 你好， train文件夹下的events.out.tfevents.1638169963.NLPGPU10-2.29554.0文件是代表什么？ 非常感谢！

您好，这个是tensorboard文件，只有在开启summary的时候会有，当你需要用tensorboard看训练过程时，需要读取这个文件才能绘图。

**Comment by leileilin** [comment]
> > 你好， train文件夹下的events.out.tfevents.1638169963.NLPGPU10-2.29554.0文件是代表什么？ 非常感谢！
> 
> 您好，这个是tensorboard文件，只有在开启summary的时候会有，当你需要用tensorboard看训练过程时，需要读取这个文件才能绘图。

好的，非常感谢。
