### ISSUE TITLE
Compatibility Tips for TensorFlow-1.4.0

### ISSUE THREAD

**Issue by renhongkai** [THUNLP-MT/THUMT#24]
I use python2.7,tensorflow==1.4.0.
The error is :
me: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "thumt/bin/trainer.py", line 466, in <module>
    main(parse_args())
  File "thumt/bin/trainer.py", line 459, in main
    sess.run_step_fn(restore_fn)
AttributeError: 'MonitoredSession' object has no attribute 'run_step_fn'

We look forward to your reply.Thank you very much.

**Comment by KelleyYin** [comment]
2018-04-12 13:10:28.825845: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-04-12 13:10:29.011996: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:03:00.0
totalMemory: 7.92GiB freeMemory: 7.81GiB
2018-04-12 13:10:29.012047: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 2, name: GeForce GTX 1080, pci bus id: 0000:03:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "thumt/bin/trainer.py", line 468, in <module>
    main(parse_args())
  File "thumt/bin/trainer.py", line 461, in main
    sess.run_step_fn(restore_fn)
AttributeError: 'MonitoredSession' object has no attribute 'run_step_fn'

I have encountered the same error .

**Comment by renhongkai** [comment]
@KelleyYin  Have you solved it?

**Comment by Playinf** [comment]
Upgrading TensorFlow to the latest version will eliminates this error.

**Comment by renhongkai** [comment]
@Playinf 
Thank you for your reply.
1.The latest version of tensorflow needs cuda9.0, and my Ubuntu server is cuda8.0. 
2.I saw the branch of github has updated 'Minor changes', so what branch should I use?

**Comment by renhongkai** [comment]
@Playinf
Thank you for your reply.
1.The latest version of tensorflow needs cuda9.0, and my Ubuntu server is cuda8.0.
2.I saw the branch of github has updated , so what branch should I use?

**Comment by Playinf** [comment]
You may find commit 2f5c2881220b6f81f864cf045783f062b6022e38 helpful.

**Comment by Playinf** [comment]
Sorry, the commit 7956f2a52aea2b83f5f237d9e496b58dcb8e1626 is the latest one that support TensorFlow 1.4.0.

You can also use the following patch codes with the latest commit:
```
        # Create session, do not use default CheckpointSaverHook
        with tf.train.MonitoredTrainingSession(
                checkpoint_dir=params.output, hooks=train_hooks,
                save_checkpoint_secs=None, config=config) as sess:

            sess._tf_sess().run(restore_op)

            while not sess.should_stop():
                sess._tf_sess().run([init_op, ops["zero_op"]])
                for i in range(update_cycle - 1):
                    sess._tf_sess().run(ops["collect_op"])

                sess.run(ops["train_op"])
```

**Comment by renhongkai** [comment]
@Playinf Thank you very much. This problem has been solved.

**Comment by rgwt123** [comment]
@renhongkai Can you tell me how you solve this problem? I met the same thing 'AttributeError: 'MonitoredSession' object has no attribute 'run_step_fn''. After I use the patch code Playinf describes, it can only run 1 step and then another error ocuured.

**Comment by Playinf** [comment]
@rgwt123 I have tested the patch codes under TensorFlow-1.4.0 and do not found any problems.

**Comment by Playinf** [comment]
We recommend users to use the latest version of TensorFlow. We may drop the compatibility of old TensorFlow versions without notice.
