### ISSUE TITLE
confuse about vocab.py/get_control_mapping

### ISSUE THREAD

**Issue by chenvega** [THUNLP-MT/THUMT#52]
Great project! Thanks for your contribution.
When I read through the whole project. I am confused about the get_control_mapping method on vocab.py. This method seems like to convert the vocabulary table as a list to a vocabulary mapping as a dictionary. But the parameter "symbols" is not used in this method since the vocabulary table already has <eos>, <pad> <unk> and <bos>. Even those symbols do not exists in vocabulary table, this method can not add those to the mapping dictionary.

**Comment by Playinf** [comment]
@chenvega `get_control_mapping` method is used to convert control symbols (e.g. <pad>, <unk>, <eos>) to numeric ids. For example, we can use params.mapping[params.eos] to find eos_id, which is useful during decoding.
