### ISSUE TITLE
Bleu Score error

### ISSUE THREAD

**Issue by sandipjedhe** [THUNLP-MT/THUMT#53]
I have run the below command 
sed -r 's/(@@ )|(@@ ?$)//g' < newstest2015.trans > newstest2015.trans.norm

And the run command for Bleu score as
multi-bleu.perl -lc newstest2015.tc.en < newstest2015.trans.norm > evalResult

and occur error as
multi-bleu.perl: command not found

There is any package required or any more parameters take

**Comment by shuo-git** [comment]
See https://github.com/moses-smt/mosesdecoder/blob/master/scripts/generic/multi-bleu.perl
to download the required script.

**Comment by sandipjedhe** [comment]
Shuo-git, I don't understand what i do, which script to be download ? There is any other option?

**Comment by Glaceon31** [comment]
The link provided by @shuo-git is the script you need
