### ISSUE TITLE
Decoding output format

### ISSUE THREAD

**Issue by sandipjedhe** [THUNLP-MT/THUMT#54]
I was run decoding command as
python thumt/bin/translator.py --models transformer --input newstest2015.tc.32k.de --output newstest2015.trans --vocabulary vocab.32k.de.txt vocab.32k.en.txt --checkpoints /home/shweta/sandip/thumt/THUMT/train/eval/model.ckpt-4000 --parameters=device_list=[0]

Here, one thing I am not understand why we create output file as a .trans extension. And how we read/open that output file. Can we open file in Text Editor?  I have use NVIDIA-SMI 384.130  4gb GPU.

**Comment by Glaceon31** [comment]
You can simply make the file .txt extension and open/read it in text form. You can also open it with Text Editor regardless of the extension type.

**Comment by sandipjedhe** [comment]
Thanks Glaceon31.
