### ISSUE TITLE
Online demo not working.

### ISSUE THREAD

**Issue by sanjita-suresh** [THUNLP-MT/THUMT#55]
I want to try the neural machine translation system to translate from Chinese-English but I am confused how to start. Can you please provide a tutorial?

**Comment by Glaceon31** [comment]
You may refer to the usermanual.pdf in the repository, which is a tutorial on using THUMT to build a  neural machine translation system.

**Comment by jake221** [comment]
> You may refer to the usermanual.pdf in the repository, which is a tutorial on using THUMT to build a neural machine translation system.

I think there must be other preprocessing steps if we want to translate Chinese to other language, for example tokenizer. Could you please add these content into the current Usermanual.pdf?

**Comment by GrittyChen** [comment]
@jake221 Thanks for your suggestion, if you want to translate Chinese to other languages, you could use the off-the-shelf Chinese word segmentation toolkits (e.g., THULAC or jieba) to preprocess the Chinese data, we will add it to the Usermanual.pdf.
