### ISSUE TITLE
Will PyTorch version be developed in the future?

### ISSUE THREAD

**Issue by Schureed** [THUNLP-MT/THUMT#57]
PyTorch is getting more and more popular, is there a concern to develop a PyTorch version?

**Comment by Glaceon31** [comment]
Thanks for your suggestion. Developing a PyTorch version for THUMT clearly benefits the system, but our first priority is to improve the TensorFlow version and keep it up-to-date. So we do not have the plan to develop a PyTorch version currently. Though, the idea to have a PyTorch version is great and may be listed later.

**Comment by Schureed** [comment]
Thank you.

**Comment by alphadl** [comment]
@Schureed Hi, the standard Transformer model implemented by PyTorch was already released. See  [THUMT pytorch branch](https://github.com/THUNLP-MT/THUMT/tree/pytorch)
