### ISSUE TITLE
Ancient Chinese Dataset

### ISSUE THREAD

**Issue by cenyk1230** [THUNLP-MT/THUMT#61]
Hi, your demo includes the translation between Chinese and ancient Chinese. How can we find the ancient Chinese dataset?

**Comment by GrittyChen** [comment]
> Hi, your demo includes the translation between Chinese and ancient Chinese. How can we find the ancient Chinese dataset?

Thanks for your question. You can get the dataset from [here](http://thucc.thunlp.org/translate).

**Comment by cenyk1230** [comment]
Thanks very much!
