### ISSUE TITLE
A question of the replacement of "@@" 

### ISSUE THREAD

**Issue by minorfox** [THUNLP-MT/THUMT#69]
Lines 172 and 173, hooks:

> for i, l in enumerate(decoded_symbols):
            decoded_symbols[i] = " ".join(l).replace("@@ ", "").split()

Whether it is a substitution method of the below command?

> sed -r 's/(@@ )|(@@ ?$)//g') 

(I test it on my BPEed corpus, but it doesn't work...)

**Comment by minorfox** [comment]
After "deBPE", the model's output file also remains some "@@", did those lines to replace those "@@"?

**Comment by GrittyChen** [comment]
@minorfox Which version of Python do you use? 2.x or 3.x?

**Comment by minorfox** [comment]
> @minorfox Which version of Python do you use? 2.x or 3.x?

python 3.x  and tf 1.11.0

thx.

**Comment by GrittyChen** [comment]
@minorfox I suspect that the problem is caused by the code incompatibility with python 3.x. Could you try to run with python2.x and then give the feedback? Thank you very much!

**Comment by minorfox** [comment]
> @minorfox I suspect that the problem is caused by the code incompatibility with python 3.x. Could you try to run with python2.x and then give the feedback? Thank you very much!

OK! my pleasure.

**Comment by minorfox** [comment]
@GrittyChen I have been tested it on another computer and it is ok.
Thank you for your help.

**Comment by minorfox** [comment]
ewsde

> @GrittyChen I have been tested it on another computer and it is ok.
> Thank you for your he
