### ISSUE TITLE
Bugs in bin/scorer.py 

### ISSUE THREAD

**Issue by zhanghuimeng** [THUNLP-MT/THUMT#81]
The code used `six`, but does not import it. And in `usage` it still says `"translator.py [<args>] [-h | --help]"`.
It seems that this script prints a score for every parallel sentence pair. But what is the score for?

**Comment by xc-kiwiberry** [comment]
We fixed the bugs. Thank you very much.
The scores can be used to compute sentence level cross-entropy loss, that is to say, evaluate in loss style rather than BLEU style.
